var GAME_LEVELS = [
  ["                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                       ",
   "                    x         o o o o o o            x                                                                       ",
   "                    x         o o o o o o            x                                                                       ",
   "                    x                            b   x                                                                       ",//portal B(takes to coins behind the waterfall levels)
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                       ",
   "                                                                  xxx                                                        ",
   "                                                                 xx!xx                                                       ",
   "                                                                 x!!!x                                                       ",
   "                                                                 xx!xx                                                       ",
   "                                                                  xvx                                                        ",
   "                                                                                                                             ",
   "  xx                                                                                           xxxxxxxxx                     ",
   "  x                                   o o                                                      x!!!====                      ",
   "  x            o                     xxxxxx            xxxxxxxxxxx                             x!==                          ",
   "  x          xxxx          o   o     x    x            xxxxxxxxxxx                       o     x                             ",
   "  x  @       x  x          yyyyy     x    x                                           xxxxxxxxxx                             ",
   "  xxxxxxxxxxxx  xxxxx  |             x    xxxxxxx                                     x!!                   yyyyyyy          ",
   "                    x!!!!!!!!!!!!!!!!x          x!                           xxxxxxxxxx!!                                    ",
   "                    x!!!!!!!!!!!!!!!!x          x!                           x         !!                                    ",
   "                    x!!!!!!!!!!!!!!!!x          x!                           x         !!       H         a                  ", //portal A(takes to box) + hazard portal(transfer to lava)
   "                    xxxxxxxxxxxxxxxxxx          x!                     yyy   x         !!      yyyyyyyyyyyyyy                ",
   "                                                x!                           x  o o o  !!                                    ",
   "                                                x!    yyyy      yyyy         xxxxxxxxxxxxxxxxx                               ",
   "                                                x!  |                        x                                               ",
   "                                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                               ",
   "                                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                               ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                                                             ",
   "                                                                                "],
  ["                                                                                                                                                                     ",
   "                                                                                                                                                                     ",
   "                                                                                                                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                                                                     x",
   "                                                                                                                                                                     x",
   "                                                                                                                  c                            o o o o o o o o       x", //portal C to box in at the start
   "                                                                                                                             x              xxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                           xxxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                           x                 x o o          xxxxxxxxxxxxxxxxxxxxxxxx ",
   "     !!!!!!!!!!!!!!!!!!!!!!                                                 xxxxxxxxxx         xxxxxx      x                 xxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxx ",
   "     !!xxxxxx!!!!!!!xxxxxx!                                              xxxxxxxxxxxx!         xxxxxxxxxx  x                 x                                     x ",
   "     !!xxxxxxxxxxxxxxxxxxx!                  yyyyy                        xxxxxxxxxxx!         xxxxxxxxxxxxx                 x                                     x ",
   "     !!x                  !                                               xxxxxxxxxxx!         x!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx             yyyy                    x ",
   "     !!x                  !                                   yyyyy      xxxxxxxxxxxx!         x!!!!!!!!!!!!!!!!!!!!!!!!!x                                         x ",
   "     !!x   o o o o o o o  !                                             xxxxxxxxxxxxx!         x!!!!!!!!!!!!!!!!!!!!!!!!!x                                        =x ",
   "     !!x d o o o o o o o  !                                            xxxxxxxxxxxxxx!         x!!!!!!                !!!x        yyyyy                            x ", //portal D to floater
   "     !!xxxxxxxxxxxxxxxxxxx!                                             xxxxxxxxxxxxx!         x!!!!!!                !!!x                                         x ",
   "     !!                   !                           yyyyyy            xxxxxxxxxxxxx!         x!!!!!!                !!!x=                                        x ",
   "     !!                   v                                     T       xxxxxxxxxxxxx!         x!!!!!!  o o o o o o   !!!x                                A        x ", //transfer portal(level2) takes to lava box + hazard to lava
   "     !!                                     yyyyy                       xxxxxxxxxxxxx!         x!!!!!!  o o o o o U   !!!x                      yyyy               x ",
   "     !!                                                                 xxxxxxxxxxxxx!         xxxxxxxxvvxxxxxxxxxxxvvxxxx                                    !!!!!x ",
   "     !!                              yyyyy                            xxxxxxxxxxxxxxx!                                                                        !!!!!x ",
   "     !!                                                     |     |  xxxxxxxxxxxxxxxx!                                                                       !!!!!!x ",
   "     !!               yyyyyyyyy                   xxxx!!!!!!!!!!!!!!!!!!!!!!!!xx                                                    yyyy                  =!!!!!!!x  ",
   "     !!      @                                   x!!!!!!!!!!!!!!!!!!!!!!!!!xxx                                                                         !!!!!!!!!!!x  ",
   "     !!    xxxxx                    |      xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxx                                                                xxxxxxxxxxxxxxxxxxxxx   ",
   "!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx                                                                x                     ",
   "!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                                                       xxxxxxxxxx                     ",
   "!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx                                                      x                              ",
   "!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx                            "],
  ["                                                                                                                                                                  ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                                  ",
   "                                                                                                                                                   xxxxxxxxxxxxxxx",
   "                                                                                                                                                   x   v       v x",
   "                                                                                                                                                   x             x",
   "                                                                                                                                                   x             x",
   "                                                                                                                                                   x             x",
   "                                                                                                                                                   x             x",
   "                                                                                                                                                   x  o          x",
   "                                                                                                                                                   xxxxxx        x",
   "                                                                                                                                                   x             x",
   "                                                                                                                                                   x             x",
   "                                                                                                 xxx          !xxxxxxxxx                           x             x",
   "                                                                                               xxxxx          !xxxxxxxxxxx                         x             x",
   "                                                                                            xxxxxxxx          !xxxxxxxxx                                     o   x",
   "                                                                                        xxxxxxxxxxxx          =xxxxxxxxxxx  o o o                          xxxxxxx",
   "                                                                                        xxxxxxxxxxxx          !xxxxxxxxxxxxxxxxxxx                               x",
   "                                                                                   xxxxxxxxxxxxxxxxx          !xxxxxxxxxxxxxxxxxx       yy                       x",
   "                                                                                    xxxxxxxxxxxxxxxx                                            xxxx           J x",//transfer portal j to platform
   "                                                                              xxxxxxxxxxxxxxxxxxxxxx                                             xxxx            x",
   "                                                                            xxxxxxxxxxxxxxxxxxxxxxxx |                                       xxxxxx!!!!!!!!!!!!xxx",
   "                                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!                                xxxxxxxxxx                 ",
   "                                                     yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxxx!!!                            xxxxxxxxxx                     ",
   "                                         o  o       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    o o o o o           xxxxxxxxx                          ",
   "                                        yyyyyy      !!yyyyyyyyyyyyyy!!!!!!!!!!!yyyyyyyyyyyyyyy!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               ",
   "                                                    !!              !!!!!!!!!!!!              xxx!!!!!!!xxxxxxxxxxxxxxxxxxx                                       ",
   "                                                    !!           !!!!!xxxxxxxx!!!!              xxxxxx!!!!!!!!!!!!!!!                                             ",
   "                              o o                   !!         !!!xxxx        xxxx!!!              xxxxxxxxxxxx!!!!!!                                             ",
   "                             yyyyyy                 !!       !!xxxxx             xxxxx!!                       !!!!!!                                             ",
   "                                                    !!      !!xxx                   xx!!                       !!!!!!                                             ",
   "xxxxx                                               !!      !!xx       o o o o       xx!!                      !!!!!!                                             ",
   "xxxxxx          o o                 yyyyyyyyyyyyy   =!      !!xx     o o o o o o     xx!!                      !!!!!!     oooooooooooooooooo                      ",
   "!!!!!!         yyyyy                y!!!!!!!!!!!!   !!      !!xx  o o o o o o o o    xx!!                      !!!!!!     oooooooooooooooo I                      ",
   "xx!!!!                              yyyyyyyyyyyy!   !!      !!xx                 f   xx!!                      !!!!!!    xxxxxxxxxxxxxxxxxxxx                     ",//portal F to tunnel
   "  !!!!                                          !   !!      !!xxxxxxxxxxxxxxxxxxxxxxxxx!!                      !!!!!!                                             ",
   "  !!!!                    yyyy                  !   !!      !!                         !!           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                             ",
   "  !!!!=                                         ! e !!      !!                         !!           xxxxxxxxxx!!!!!!!!xxxxxxxxxxxxx!!                             ",//Portal E  to portal F
   "  !!!!                 o            R           !   !!     !!!!                       !!!!!!!!!!!!!xxxxxxxxxxxxx!!!!!!!!xxxxxxxxxxxx!                             ",//Harzard portal to lava
   "  !!!!                xxxx                      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!xxxxxxxxxxxxx!!                             ",
   "  !!!!                xxxx                     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx       !!                             ",
   "  !!!!=            xxxxxxx                   !!!!!!!!!!                                                                            !!                             ",
   "  !!!!                xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                          ",
   " !!!!!!!       @      xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                         ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                         ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxx      x!!!!!!!!!vv!!!!!!!vvv!!!!!vvvv!!!x    x!!!!!!!!!!!    !!!!!!!!x           ",
   "   x  o o o o o o o o o o o x      x!                               !x    x!!!!!!!!!!! o  !!!!!!!!x           ",
   "   x  o o o o o o o o o o   x      x!                               !x    x!!!!!!!!!!! o  !!!!!!!!x           ",
   "   x  o o o o o o o o o o h x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!! Y  !!!!!!!!x           ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                            yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                  ",
   "                                 v        v        v           v       v       x                              ",
   "                                                                           x                                  ",
   "                      yyyyyyy                                              x                                  ",
   "                                                                                                              ",
   "                                                                                          vxxxxxxxxxxxxxxx    ",
   "                                     yyyyyyy                                              v!!!!!!!!!!!!!!x    ",
   "                                                                                          v              x    ",
   "                     K        Z                            yyyyyyy                                g      x    ",
   "                          |       |            xxxx                                                      x    ",
   "                     !!!!!!!!!!!!!!!!!!!!!!!!!x=                       Z             xx        o o o o o x    ",
   "                    x!!!!!!!!!!!!!!!!!!!!!!!!!x=                  yyyyyy             xxxxxxxxxxxxxxxxxxxxx    ",
   " !!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                               ",
   " !!xxxxxxxxxxxxxxxxxx                                                                                         ",
   " !!                                                                         x                                 ",
   " !!               Z                                    yyyyyyyy             x                                 ",
   " !!                                                                                                           ",
   " !!                                                                                                           ",
   " !!                       yyyyyy       Z   yyyyyy                                                             ",
   " !!         @                                                                                                 ",
   " !!       yyyyyy                                                                                              ",
   " !!             |                |  |                                                                         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
